apiVersion: v1
kind: ConfigMap
metadata:
  name: eureka-cm
data:
  # if you want to deploy n instances of eureka cluster,
  # you should set eureka_service_address: http://eureka-0.eureka:8761/eureka,...,http://eureka-(n-1).eureka:8761/eureka
  eureka_service_address: http://servicio-eureka-server:8761/eureka
---
apiVersion: v1
kind: Service
metadata:
  name: eureka-lb
  labels:
    app: eureka
spec:
  selector:
    app: eureka
  type: LoadBalancer
  ports:
    - port: 80
      targetPort: 8761
---
apiVersion: v1
kind: Service
metadata:
  name: eureka
  labels:
    app: eureka
spec:
  clusterIP: None
  ports:
    - port: 8761
      name: eureka
  selector:
    app: eureka
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: eureka
spec:
  serviceName: 'eureka'
  # n instances
  replicas: 1
  selector:
    matchLabels:
      app: eureka
  template:
    metadata:
      labels:
        app: eureka
    spec:
      containers:
        - name: eureka
          image: pontxo/servicio-eureka-server:v1
          ports:
            - containerPort: 8761
          resources:
            requests:
              memory: "1Gi"
              cpu: "500m"
            limits:
              memory: "1200Mi"
              cpu: "500m"
          env:
            - name: EUREKA_SERVER_ADDRESS
              valueFrom:
                configMapKeyRef:
                  name: eureka-cm
                  key: eureka_service_address
            - name: ENVIRONMENT
              value: "prod"
            - name: JVM_OPTS
              value: "-Xms1g -Xmx1g"
          livenessProbe:
            httpGet:
              path: /
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
          readinessProbe:
            httpGet:
              path: /
              port: 8761
            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5




#apiVersion: apps/v1
#kind: Deployment
#metadata:
#  annotations:
#    kompose.cmd: kompose convert
#    kompose.version: 1.7.0 (HEAD)
#  creationTimestamp: null
#  labels:
#    io.kompose.service: servicio-eureka-server
#  name: servicio-eureka-server
#  labels:
#    app: servicio-eureka-server
#spec:
#  replicas: 1
#  strategy: {}
#  selector:
#    matchLabels:
#      app: servicio-eureka-server  
#  template:
#    metadata:
#      creationTimestamp: null
#      labels:
#        app: servicio-eureka-server
#    spec:
#      containers:
#      - image: pontxo/servicio-eureka-server:v1
#        name: servicio-eureka-server
#        ports:
#        - containerPort: 8761
#        resources: {}
#      restartPolicy: Always
#status: {}


#---

#apiVersion: apps/v1
#kind: Service
#metadata:
#  annotations:
#    kompose.cmd: kompose convert
#    kompose.version: 1.7.0 (HEAD)
#  creationTimestamp: null
#  labels:
#    app: servicio-eureka-server
#  name: servicio-eureka-server
#spec:
#  ports:
#  - name: "8761"
#    port: 8761
#    targetPort: 8761
#  type: LoadBalancer
#  selector:
#    app: servicio-eureka-server
#status:
#  loadBalancer: {}

